name: Static Website CI 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest # Keeping it simple using GitHub's cloud computer

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

    #  - name: Setup GitHub Pages
    #    uses: actions/configure-pages@v4

   

     # - name: Deploy to GitHub Pages
      #  uses: actions/deploy-pages@v4
      - name: Check Website
        run: test -f static-web/index.html
      - name: Upload Website Artifact
        uses: actions/upload-pages-artifact@v3
        with:
         name: static-website
         path: './static-web/'  # Uploads everything in your main project folder
         